/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VanillaRouteImport } from './routes/vanilla'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ExoticRouteImport } from './routes/exotic'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VanillaRoute = VanillaRouteImport.update({
  id: '/vanilla',
  path: '/vanilla',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExoticRoute = ExoticRouteImport.update({
  id: '/exotic',
  path: '/exotic',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exotic': typeof ExoticRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vanilla': typeof VanillaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exotic': typeof ExoticRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vanilla': typeof VanillaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exotic': typeof ExoticRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vanilla': typeof VanillaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/exotic' | '/sitemap.xml' | '/vanilla'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/exotic' | '/sitemap.xml' | '/vanilla'
  id: '__root__' | '/' | '/about' | '/exotic' | '/sitemap.xml' | '/vanilla'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExoticRoute: typeof ExoticRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VanillaRoute: typeof VanillaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vanilla': {
      id: '/vanilla'
      path: '/vanilla'
      fullPath: '/vanilla'
      preLoaderRoute: typeof VanillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exotic': {
      id: '/exotic'
      path: '/exotic'
      fullPath: '/exotic'
      preLoaderRoute: typeof ExoticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExoticRoute: ExoticRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VanillaRoute: VanillaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
